//Data		
	const data1 = [	
		{text:'The Fool</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjJrH2GGEov-O57Cd9O-JLmREwAE-KwAyAbrVtifIefXQS6oNf5V3fcLz219z72Fbj-8yS6YaeedXa8k9ntknyCyyU3NKd_Cqlg_CI-kpxupxglp7rqjkIUUbxR-6ndLAsV8MTDEdV6YFh9Y92XRG-6g4HC-_TMtgSOX1BJq1b6afQ5BmPpWLav4geq25k'},
		{text:'The Magician</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhWT-FdgcCIp-K8PYhgxJy4ULTLUy9UKFSYXurlftQPiElKrKXP59phuh9Q8u3dlJvGZQh0LzuneNfPYbGfZIHETTtQZ2KguucWYAYzE5Ku-TaS5VnICuuaUXlLVvLuSqCMqdAvsUWLPgp4-iUzZCvLC25aGMMXPJBKvB27nJ-38tAK7e0kwkjGRcNHwRY'},
		{text:'The High Priestess</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgYFck6KLErgF_epGgqCQzCRujhESpSGkJMVmjn3E0-Rr9zm9PIi_T_EmJpER-duGccWs8fJUgpPQ7CzagpMXTAc2VFzvUdNAagmz-v0HfPbm-k3L6tpClpmHr1lzU5z5vwDqMWNHoos75PqiUjeTMUJZF1olz4KCiitnhCGZg8rfRf8Q3HVKz4zW-ej5M'},
		{text:'The Empress</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjzLSVlM19zF8dZ0xVsiQIdcbEpeSkvj6okFegPNoSpz9oP04hEvlOYmLytlDPWiexuiFuZKsLSkEqowJQQ0dFbR0zh6ERnyVH80niSvVveMha8FRUiCGutOePoy6i2_d-YXG-4vZpaxoLvkTtOAvo01pCrA9xi09jKia9ZHqquCsu9LV3oXrX_Tqj9AJ4'},
		{text:'The Emperor</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhWD228X2MKZpUhfYAp9RiC_a6hTOmJC1YM8rQjRFOfDpcykWp2WlKFrXhi8QZBabfb_yOY_ikvTYpElQuAQTW2SiwFrLh5ylnIijj8RfWZ6Ca435riCCizeJbELKyMl_9lIdhLrtM_91quQgTFNbJgJ195ZPjORWybIVtdDGvZZrRvh9TChFhrnjN9Q1Q'},
		{text:'The Hierophant</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjRGpVdWeJoIjzNGfWh2pmLMO6b6DWcCFIpLgr9lEehJrfvvOhGscCb5QJ9t33Mn_ffzZjW8WaPKgR_oQa9-Sls8-blf4j2pN0RWBCxJrual-IklD0pkoj1TRvprBNl8S5h9IQicfXVNQxS76E-foD7TVrLrSZpRVmCfv35HDRBaBQ7hEnrOYAkmT4zm2Y'},
		{text:'The Lovers</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgCuc6Np4Sqh6kwfQyzPxQeEUnoARCEzwdcrh3b5hHL_J9Z9HvO0cQqpHznvmx99ntHJGYJdbqah7vSfCiKYwnaE2MiS8a6RJ79CTvJcKVrOBo3dPNpyGJC2LvOMGyvGTEZDXwgBcgIzsnwwz_U6Fl2uMMi6VRUyZUwuxpn3-OcTtPTxmPvZSt3prJzdY4'},
		{text:'The Chariot</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiBqYCKjyEtf0_tzGuC3DmBrEZpZs4HNG8ux7JHBuPHXm2mUrbVzas3SAaqtmmFe7Ysr0saNoLuzVtDegLPFCitfPYXsWED5mznVrgtQE5e_ZVGW3J6mNJUJUpKiL8d5ym0usx3Ac0qVxyWcwOvE1uoLbBxETSm-XMVgkXpnXo88AjQ9TvYvFXiIA_PPJM'},
		{text:'Strength</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEirK56PqY5Vg17YtEyG1vSrsv4m_Ii-V_WwPvZQcGLVc4XfrHF_RLD3f2JmDx72H7Y5HeoUQ7zlQ337qCbKOFCiylJ3ywZin51AKitm-hhpKMuE_5jhrjrYZPz0OlvBulMAk0vc0JLrNQ-xkyRe-0710Yr8E2Z6EuWx4HoLQG1wdJDH1CtJSK9sgd4CupU'},
		{text:'The Hermit</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEh_e__Uvo4jk7t3uuadCicBm63Dd5bm1ZeQ13WNdslHGU1f9tblR7fJIF0SeBTcD_YGFXuM0npVCK5cjVivUb6k-q8sDb5eq17WLtn9yM0GKulVBD3jaC4KVZK20RoOqZKwZpSz_QAlQZEnjM_BkX9r8XxM4idwcyGVS59jgFLN65uzBicxpD0IQHVhAEg'},
		{text:'Wheel of Fortune</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjUMTVKp0WwhkQpnUMlLgE3G72SDuH3MADQIVOjOZngPmjyIQPw2wtmsDon7pdAdS33ZXAn-0cmHKSziqZIe9QNl18pfzz-8v7i5Xd8RUdrbtErmfP_wPxIl_1qbQB6IRq-YEwFZq7ZTovLBgsnSCTrn223VmKJJQcdCBbOxedkL33rXp_WJ7YBF3OLe_o'},
		{text:'Justice</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEh5GS8MDHCGWA2-ZWqAkKPDtQs6HA1fXIIJNW2zV6EGI_hsod0fismpFvpPnqsxOFI_1ve7AOMhgN-gzb1AP0jC8fvBciz-J3ey3iQGtDRhQDKX_VT-KNZ39GGnFtjw66JhlyoZ9NWtjK0HGiDXYNWeRW28z58DFex_8indFqDjq9jvhCzwBqYfhe1gElc'},
		{text:'The Hanged Man</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhnyO2HvM9vYZ9ygQ11URMaV8XGWl1ucGNpunyEHr1CeVughrkZ1AWQk-ovvCN_iFYdyYLH3gd7zmdh6-LlVbwM1Ygr7W6MYv4tgXJy-xqVjW2Aoc_WnZN9-vMNhi2dHDW-GMUDZfhYSdd1O3AmwcwjNidWAL4eyceGHDAg2c1ceYE0WlsLyq8p0NKr-s0'},
		{text:'Death</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEg1JuZouQGuIpf6dPS6Prvb3w_9qu6RCLQId8GuVXF0rowet4bLrSzeY0jTTxMlBuR-43yQrQPvZBTUuB9VRADTOBScfig6a9XX3F4MIb7MZ9oLXjNjZlFlSxmQHo9pBAykIR47540sWhcOVUdpvkua5x_HtU1ba77um77-lgOqETf9Nfep7K1BEMY822s'},
		{text:'Temperance</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEixXTVzMJUn2JCEDtcVOADuwgqvEbGQSYdezLwBgeQg0G1AdQpwv7Y5CTcqKBfzd5tA9w4VwExqCriyjNszN0A6nwHs5_gMUF_8_YQ_V7Egcsn78Q9qdMsc_SSvhkp5GhPL4dqcN7_r9HktawZF0dJGRrGxOtgXCBe-dIJPOWhfbb5Jurg-hZtBp4OnwaQ'},
		{text:'The Devil</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhAYiFC-beZNZ3WvCDujPCuP-XeDYYalFPMEkaJfgb9AV4dAjUoSn-spG8vFM6qwU3AF487ptDFC2UWap2DgOlIVCAOXJY-uA35VSiidGQgMYzb2t5zO0Iu6N6cx8AKyd6J-QBW8psv0Te-dEzkLJZquB-8ZB9tb9Y138NfitGS9eXCXbWGoWt0uvasKbk'},
		{text:'The Tower</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEh_1gWQ8AS9FSl5FtNN-O4yR06zZnvRbPd71Nre35Xa6NGtpb8qxxAcaf3DWSUmujc9dOZhaldTQUPkEj3h7LZyGmRgWd_23GHjEMV4cfI-i49Zd4sHSfYvc_0SSGigTLHJiqw5ptEq1JxVbGUB3IMSdQTZsqXNmooxazx9eXjyTNZXCOshuRKD-DXWv_g'},
		{text:'The Star</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjU_JbrP4r2unLjyxgMtrGVDAIL5r9huyLZPXtNiS5xUcW-0L1U44mbbAHZO4iVvfxyBEdoGvvJQ-Xa6e9L0ZDFJgB3lnT8f6TklyNEPGP4ukreLWrGZqHwVwR7OrLBnHtK6bqPHWPYBum5S3QecIGiegCk_DBzxZU4OI6lDYylUCEVB9SuE96qfhI8YuI'},
		{text:'The Moon</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgzDbypho7uuf3Sqqf1XGYwcXAZ0VqVS4RHNKIwH8BdPT6RW5KuFcNoZZCrQ8Fq9kxjVyiZIsnOHOND0Op138aCbm-iFQSDxX0QqAY2T5z_GP-owJL6R560U1bc4F5GH6NollFmyATXO4v5k1LYAxgBv8jhekUk_Ej3-3i7FKx22bdOBKbAKCofFdbB6ic'},
		{text:'The Sun</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgyOVPUFzF4eQKNi7vJ3LE8Uu1cVqYY4llYB3cbBMIj4CJIqpzqJB3lPCOPm-autF0fsWTvFUD4dizxBDPn0h0V2HkDAbutBeujrAcAoqg86S_tstLj04VIFB0r0n5lyoBqFLo2GPtI0930aX_78Z9C5bmkhhGAA-3-x4Xxe4UUaYuSwQnDu0WgtjC7YSk'},
		{text:'Judgment</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhC1tO_gipsCAweCA-Lrgx3MJHQPzXbznuVtGXxJz1wE5AS-_dj-GOArZ0XRq9PeFQOWyk7LYiPTTLdDCgki4xe0so_CDL0xceElE8utbXqN93hYmZwoagMX0HXIOBi2Z5cthMisqJDkBeyAf5mSU6lgJxHeM-l_nVYFybSfzmmBO-2_nUzIownOjjaKjE'},
		{text:'The World</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjURrml282iAUkQDvlkxCDYt3ogPrOMh7k9DJnodvMV3niWk2LmDH-onKR1SUbBfQKLor1GJERbdjzTGTz-VL32j4QloA6pF6p29k4dGDH3sFB4crzUSTT1VFsv3X3zjHm6aMjq8fxnDGslxHpqevtm3ouVsLxoU8F_ivoT45iavzGXUI21KYQ1wQnPJ4U'},
		{text:'The Fool</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjB-WNX8pHt9QKdC7jYimTMf7qr-c7DnHpyJhJ_qNA9DLx4zUKNsTbSUXN8Jj20ZKzHeoOS4xDd_YqmUg4YrXDVgjh5XQRbbzDbiO3HaaA7DfjjZFYZ6aZugWWyJHc8c0bJ0wQCuUB_7Od-4w_yYlgZveIvB3N9Ofvs0XizQd-Kw7MdU34Rmg4wxOJ2nEc'},
		{text:'The Magician</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEg245as5jmg6Ltx-xmcV6KNjYW7Z-0uXsysxXFBI8YOfx6Z8Wa3tDheunSpJ3UwpwtidkaY-kRhOLlFZ3L3O2_yNvdWakJCLacm3TXdZrnOJ-UegUNawakxYn9bdETslvX9NILwlnHRXBrG2L_sfRUDzgCE2SEq3Ab8Z4qxE7Ly_iBseOncEMUIU0j20jw'},
		{text:'The High Priestess</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEi-uKmZAfUlHvpmcVlw7HaELnEKMh_uc-Xxcvek40IdMj0aCt0KXrY2fudroWhyIIWvWUUWMoNvWluyWRdmaL2u9IMGsbMWGrcjbf6xPebYEy7_-PKnRi1eIZ50O2OXIVS2OkH_dGtzQPnafT7s1PK1IHc7vCyw6Ow15u-VEQkq2LItLF1CXhdpr5iRAhk'},
		{text:'The Empress</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjJjrBZhJbmPCK5vrXBiyR32q0sfPkiHVANJ-uC7SORSELVi9AmsBBv2nlsySFo-mzeJcVrNipKxhm-GUSbxHE7E131uEt6UUccX4BAlEyrXOvSDmQvUVICFn1QTDgsDF9-e-INTylBLFM7KskSDZgOepJWu9kTUnDZzybkJ4PQRnFDAR-xiACvxnSijdk'},
		{text:'The Emperor</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEg_o8g60P523QcsmQ39KV0297PcD18LmhWKKXi04au6eVFIr_hlBmdYQOoZqjBV5dC5f0yYbrexx_BGdOeGU2DznMeBSsykOjLy3bfXi4mwb-_Ry6WrIa8vWlRMksbbkH77Xetma-Q0vixnJFTEOb5CxRiJmmn2-VOaI0gGKajnuDmUoP71_8hj_TZTGCo'},
		{text:'The Hierophant</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEg-bkj1TYwyXaycUz8OQYt0n_3KWZ3NLjCBz2CWGdoWkpVNv3ZeKQ5OyON8bsgwxV-FEJaYc5ZVCjqIFvW4hTqpWle6KoiIlJWQ0WqKvzGckcH8nh0cJBwDVZDaM5lPGMYjo7g778bBm2AOdBgEmm2zmhuStLD1EbGKoNdY3iteV_l58UgE2wOs9FvqqM8'},
		{text:'The Lovers</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgZdX6KTauy3Mv2i3nTb3wtY6vdAUgV8qNk-eMwG7MI1kuKx3jtZS9Zr8sqeoPPvWhUquVo4CbHx6p3EEGsPofre-DJ2w11pGws48MBfBvALBt9ubfqLY7Jkb4bYwBgnVIOmqTsZfjhOCSz7Xm0kB9iVdNV3A86ZnlyehkWjap3E_UKVEeEFKIkh90tQqE'},
		{text:'The Chariot</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEi8ngYC0WUI4v1R0uB8571allaF8AT68ZZCdOGomLeYAGY1IJYCeG-F-LvOTCTa48G8NfT6usrqmRm-lFSLUUfOge4VB7EkJ3aGmnLsdtXfN5-Sd1swjlEcdKhGYDj8nQOM63X--7AbCMX9n7psmdAoPoAg8mkZmTu-RVS4lD-4HTzZAVfJWcSwWvntDew'},
		{text:'Strength</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEizCnVzm20-zx64-TKJOBPWJKA7cjxMPmQYwhrf0RmAO3l_ARQi2u5IhUb8DenRLu0H5vtA2IScxD9vbgT3whAQbqaQM9lWqE_68dVeeJ7z9O3UBZKJ8RX_oonnySYD9qd5UwahyzfTqpI-8JSqD6NVCMzoEf1F2lct0qwTpotr-mSTHVArHtkrfk4u5-c'},
		{text:'The Hermit</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjDBnzd1jqZ1ppJ07qBifTThIwJMFjAM8gWfRf8gIiqSds7q7-F7VQeLWNz7bm5M5miPqhEHBOwDstURXapD6TlySQcSUEvem3nxSxYV4tJyP87CZ-7UYhL7JWElsb_jUORbxZIxASzrTR9GVtUATRIR5BZmGFTocxYQ8TThSEAF3_FVr2W8eELKiHwXjk'},
		{text:'Wheel of Fortune</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiDN-OUdmP4KcctfYSEifmGRD8-ONDN0H7YPotVTrDmNtO_Fsx0M0ULcu8Ns_RGhAtFQq5Z65TkfNzjyssP5MzemTH5vny1yqAzFWH2ixmyQFPOBfYIvfaydBGEl0qRdmlihF1Yc3A6RS0LuWT0obmpG3J-fCMtMI6jJYrjkMfFlodQpJ5jNi8IP8nBTgI'},
		{text:'Justice</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiAUMdcHPVGbvQGXcneb3jG7YHRfWW1tmLUkIqC4xugYDUBwhKu4GSCr6XMHER4BsaKDxYI0quNAetZRcgzMWEuP6Uh2I4XUXUOncAcDaYp37-XLY0A-SA65Uk4lmOpdKc-3i9RhRkrl3MCB0CgMyX-ifmBs-CCpKGQcA9n57jcJi7He_H4_6sQNtXE4ps'},
		{text:'The Hanged Man</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhThcTLGJ1ilRlNjDjWksgF9OsBMcsAUU6JuIcEKb0kZEbZueC8IsKR0njsac3-iaXAaJDTTfBK_uCH-7YfAwO6npJFecDBlskRs7JQvGvGebd_FhQH2CcoBNuaZwRyaVPJbqXzlFTDxV-xxdhbgsgB96UVIgd_jXqDR6NRmEJtwYIGWn7f-gemBqA5rTI'},
		{text:'Death</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEj6tFKs8TUHxFFix2KeRvcrcxshUH9AKJ_wW7u4lPPdIuDyESSoRXaMeyIp-uxWPqpgTq--LJAXKnzNTy-qMwx4N2nRB3a7dECzY0mb1o1JSr5gGGURxcQeCTfuCkrUhRlzXR9Qx0VQBrbQDYUBXeyt_bpSQbfU1mRmAfyvfrmiIyNzWmnE2lDsNaf3LV4'},
		{text:'Temperance</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEj3LeAW3SNV5IYpoHsHXHjV3O-nnOLJZtmiMX7R3eCpRGpW3XOY8OlNy8bK7hAbcbPc6BUqR9doxeSKPr5-yniuKs_SIKdrTl43SFRIqA0NsukuVPPfL7OO5ZB65-4lPQT8aFJb9jsCNJiPLrcYVfXFTsVIAw-GOzWD0QLiiqGoUpQeKRb5O7LEVQ7Bsuc'},
		{text:'The Devil</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgKWV5fF5k080AbdovAKUxShRqx-uy92-OPHjpHQseJaKj8qb-UEMUGv_ue3DjrIeGoeoydW_Ur4GjyIjptfg3hesC12hyr6NsQ0Z8jy2oSUrSM13IYOM4bLoyMWa3ZydrRqJhVaXBPy6f3sA8VFJIyA_tE8qp_gUjKO-2Y6iBl5xD0mZA644eOVAZWAQQ'},
		{text:'The Tower</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEh33w3nyQL9kLl6qrRY6ZSYngiBLQlH7w5A_2KzRprC-NSh-C6GRybbqduufJXjYyHCBbP9qsjh_9jrVv74Hn8vyWXD5cSS-93EgzB02cvwY2uQUGh83zVOuWBmaa6u2Fk5XnsGqyJQquxHL0aMhTW9q-sRE5PttMJ0ekgNwtFYugVLcpp7r_Hec1xYKkk'},
		{text:'The Star</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgrCKC5f8VVg5fNKq7pyvgROj3vSt0qHxb7of7pOVI8uEH775XACcBnwCe9MulLBBVoOFYkVWjB8dpa1g1OQUif5aasF-tXRu5FepBMyYz9cmVDCqLJC7_6DXKN-os_Mg8ofT2BuWqbV6UiGiTV-Q5sevurRxKN4okVq_-EpUhrh_utFfqMLDN19fgklT0'},
		{text:'The Moon</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEh8UNq4vcqnsaaPbpPHKQ2dmy-11rZZkkVKqQ05QKHFxgTfO82LZiBNPwrOBfyGqFdrV8hS-w9XFqrD9GldiUoDWtKQqDEY-vYZqFje91vljrabBnVN08ic2ox37mm4RI-JB8rcnQM4lQzqnhDIqdNOaTuyebc1ztyWUuZftUJOCRSmR86HiZfHS_HdyQo'},
		{text:'The Sun</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgBgPkEtf0TwLiM5mICvTxE_tsmPl2TQQPOC8ekif7O1C8-GsIQWQ1WZMj-PMzBDssnJczPuZMDPtZHUwKOfsQJ3MRgp-DtNXJFZPyy27QTs_PcZLU7KhQI2EC-ff52j8HEKYgbLxoGvOJcaQbtDG6w7HJ-cjOfHEeQKY4DDKfbU_mikAFj1-rqK3yh5Pg'},
		{text:'Judgment</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhXX63pHZbbw8PtZTE3Ua_a7GqUcoeqOpOSfmHGNjmhcKWBP3U92V_VZujSZy0AraM6A9P_6ZYA4-DzF0jqz-rMuEZg3VQsjDkjN5BCOwZ58tfARy8vL88qQWz32s8FMnRqGfQDvtREEm-vEZcwq1G36NgmdXW3iuXrbOcNOj39_YtJ66zARIQ6NacjzMs'},
		{text:'The World</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEi7NmLaOZYY9XZuk0xaVKBZjKVIUbDu_edV4g3H26bdDM5yYFFpCZWph-i3piAgRFsE_HfQjt3GHreBI5fhMNt036OTJEdESJKDT_88zIUNxz5chumZopYYxMqSpzG1QCK_i-JnAgqyXShKf0LuGRG6i5-ZSf1yIKLHTsdjWuuadOTroSzt0kIa1L4VQ6Y'},
		{text:'Page of Saber</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEi0p-ZRCVblQve-9fLgxYXdy5IrHNs2QvzELNQMBxwnXXrKZPDrS-C4R-Ws1HuZ1a_U7tTVV68CbBUlhowexZmbeh15Z0roks6ZKkwsjhTLGNbERI8KOQ86QhlY7E6XGkb1VKtWijb1wTqiADAuyNCgUbmp3zvbP9Khx4v1hMUSKzLwqU6eSMsswdran_w'},
		{text:'Knight of Saber</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjc3G3tN0BhU9tmL0b5t4h8qByvITuVxyBP1yol-aZHjx-O5Ad6esxCBcfgyxk_rteXdpkUwZ8Z2I3Tgp6o5RLCRH4PGlFnXKwM_08E-9jVPIA8Aem5j-l7P7TgPax0ZPrMP18XzDZ6auEAEa3l2bLjWR3LvRqjWI8ySWcqkEyIwjWEhI7lgYnLl_lTF00'},
		{text:'Queen of Saber</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiBwMmRs_LqaXjwR0JahNc4qe2yOkY8UVXmg8aBVfKo-_r6C1hozoyk5ok2NPAG2NyVQh9J62FdIDv2Xa0lbYNl2xNuDk4aDsXOaun2nD-FBbZ7Do_NR1UsNzlqadVmsGVCn9vYIjySwi8155Hxi9L4vtJDLJYyHzcw7ayjPcsiHQX4jFf5F-vBcwltzF4'},
		{text:'King of Saber</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjmeExjBYpor6J150H1VwDjqJ8oJ6WO8xxeFXi4OfLvm3z0CtZimE9999YYRajzgGu9f1Lslhu8ClLereRZNOHBFxeAH_HtBYU99sNyazHOfWlnkRAFPhhQHnPsyN0u25tgZUBlZ2dw9XgfBIMIdBweiXrKgLegGUSznmPca8pRMTWilOJxNGTaxnQEQW4'},
		{text:'Page of Archer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgEtpc5X02KcFYtZdnwCtRFxD-yXc5x5wrnLuDyq3KPcjmevIarn-iFa2rY-gj-Zyfh6lYH_0oa6_XP8HD_Q9JvRGO-NJR7KktoVO7Kygrmqawa7r5VgkMFZ_tU0sRtpepETJG60JkzyWbdVo4bR1b5L6q4IvLzMXpHKKMup7_nYRuR49fhNADI_l4JdWM'},
		{text:'Knight of Archer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEheJ7MfpQNWGRxXl6_W--kuphpGZVPoC6sqbMNnn0j7pVYXf26_BTWXVDK2SOPwanN3ml6EQq9CRSWEb3DIjoMvjzzGcMsqPSsAO2h4iVkcFxac_i56PReiZO2YSBh_wZx-S4IGVbklf6d6qavAGTdxawKjW84XT-aMavW8kTV3Ebq9oj04LzWWHilWxwM'},
		{text:'Queen of Archer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEijdX2VKHrnZ2XQnyZp0frnYuKyEviD4MhWUEUw4s0xUUgaOpdKROXRHDb8cjS2T5J5nJgMHtvYQcyLOpmq61XN3xgpUrULkLtLmkD3fR91K-1Q_17iXEVnhc1n0GWSBRrfj2Z1VMFn4VEgzjXaIS1soxWW0-qV2lS1vV9P8J1vVZxhjIamBmeo-D5j2XI'},
		{text:'King of Archer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjISeLIG8MoaUUq72ipRf-yCMenG0DqLeRaxTpmBcxbSOT-TxEa5u1HBlRrFz-Wa_KYMDpDxcFX2lqOXTLLQmqHKDQC8IUOxTChludp82dhPabUb5pEhw8kKhm7nRTdnrfc-hU_m-2JLRXzLIjIOr2SEbp_C0vIdpwjOXbzc5DHhxPbrwj_WBZQCKVVoMw'},
		{text:'Page of Lancer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhq4R2QeYE6phSBSvf0mEPatOw9ARFNv88XyamDjsySKpzp5V55LtNWcxnHqNcP3Z8Pm4r02ZlSdaqPEmHbJ6F3dN-dUhv284QiSsAYXqn73Bq2-mTRTo67hK0XSyHPlyP8xiwYuh3Bk_f4-hs3HLtskR6OkfiHC5HMmj5xqxQc4v48aVyTeFTeZf3GEgc'},
		{text:'Knight of Lancer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEh8nzs1ShazGnEQVnRKRKNYDtSth5G0mr6HWzEroNPPSEIyCRTl3mRLtWv7TG2eGPqQbbx6itUq_G7hNEr7hzTPSKWsxInpphQMY_wPjUjCqJjwkejbdq1pkaWDnKjnSOOAQgvD2hXr6xM1njDlJXaQy9Lmd-113E_WMUYgpLaYng8jkCWZFUJWQvZZQ_E'},
		{text:'Queen of Lancer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhf091_oLwPMhc3Aw7xioOSxjSTe8yiG21noN3zmkXgSVXi2RVSg-gHICvY-SV16Hze1KjNsMauyWnW0jI5fOJdE5nVQB6_ehD9gf-8hrpXcOMpiNnvGMuNFn8clm_hJy0ttZPbYl0JBnhhAGipcjNzP7g-D74H-zH8ngs1mMH7c9Wov7Zcq_V4FuaSBEE'},
		{text:'King of Lancer</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgKUEJLnnskgChUnewBsrmNIAm04cACG7uR6BY_ucXdPVHvOsLVJnlIQZhuY6GX77Cv3k77jrOEozCw4LzErtw5hZhYhT6dMl9YF0zgEj0liDGk6W5zcytQUOt9hcuY58qsCp06uQgRfs15v6x7puyLMuyX-Nr8H5bR_mng3saCzO3T0qfxx6_XL8TKspA'},
		{text:'Page of Rider</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgkz0azwm9AT-E9Xl-1xPz_gNGKzBoGgrMrNNqntjC41phI-Yd0oVHRqX-Z4EYV5esWNw7OvimO6kr2_MXWaywQw4A8EA4vcw1yGv6YmU10nXjc1so6suLgjvFdYsYWP0nDnLc9TIVTmagEYnaauodxL2oY1JHwSsdtw-XhfFB8reP5SwN0RiUHm0ec1_E'},
		{text:'Knight of Rider</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhwJstD0Q2xm6zeMMBHwTJBu8LitbPNpuXgDtW3D-iXRPceAyCir6kyyvYC6VXzUPMy0TXwup5iiNqIllTQJsJ0QXJcDlT0U8S9GV6zcjV5TfPNQv6VpFpj1rZGbkMMM6vyvW8bJ94qz6yOlIuykZXfiC53mqdXMAg9qTpGOZxEPQ9Zzm64ApnDhRqAkWI'},
		{text:'Queen of Rider</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhMVt9gMmafDqOOsD65YuJmTknlJRyWqrMVYjKu-XS5st8Bg5-aeTNOTIQFY0uVOGAkNRLpMg0DX_ycKOzdtoGwP6jMhS6Hxld76p6EcKML7nHtCBMdS0c2SPF91aK9oBRUgfanC8WiR0tAyWs513NKCuDra9hFl4pGji2CgjBtO93eeZkREBWH9bCzP9s'},
		{text:'King of Rider</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgNijifJS2db07WSRw-rfVi6AhxlVF8eSK7efXLpCrQ_O6-6OWibhOlFrugT5uyGsPRChUw-RhstQu-rnjPsPGTsYp2DVHmOCZKZJXBKd6EUd4YAklSeT0xC6TJw921QKYHDgAO6OpT-wDbkh0LEryC8dWc7I2xfbh-xuRqHzXqcD2motiLRkBbTXa5-3w'},
		{text:'Page of Assasin</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiiE-Cizwsry8DNNK7q8hxQDpbIOzqeJVLGaQ22EGZk9Wd1KJkhb_bD8cn_2A1kFSvCQHNTrKIQSMayzNzIoBtJrkM5Y-vgtSil-5aSijisx5b7Mvm70zSpB1mxVrLLlJOH63OtV02rUSs1g6VoD26_C0Pb_B31QrI4zw7PYXB4qSCWV8XNyC-MGUkG_hs'},
		{text:'Knight of Assasin</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjuj-GyVBjaYZMcgeTM_hlvxsYGTH8IE5hwvstH2COtNrWcxtd4dkXX7STU6rAlMI_WqlNNk8zCDCSxY639qygXU2dk8UBCf9sAfiN70fZBx_Kr7wRC95sn-JmaDHNV5lABqVtLVaatLO7fJIxY7hOLW_sN6PgdcT0xjdDf1snhxW3nsKmuKOdJ1rxPdK4'},
		{text:'Queen of Assasin</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEj8FaauAY_cWb58tgwI7qHWR1i0Q764LbIhLaGRnP5THCxBStYaiGoNsCkla2MOe8z7EhZVeXRJ-kojpFfmZK8hNm4I7M5baCxhHnuSIgDy-bDdm5_uVKvyu294a4mDu-jucsJaOpfriZd3EL19Nf1fPb3g-KWbWWF3PpXo-efZ5zDEuQ8JT_4fgHJkU48'},
		{text:'King of Assasin</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgZCH6Jn91xQ9SYN87X439ZVycK_teJwWAqKvSAc_z30mbfIZhoaLhelFMi9SAaDtBQ3cqsgr5L4gpRNgLPlG0M-Gcb6mGcXAo_dqYtEUqfz0-hItLZg2xxvAFeXHIl9hShQ55hBjhgRHWFrPn3uPgEbk46xy3TJgZQo75v9PyyArZZ4OXj3h3LMJbf1SU'},
		{text:'Page of Caster</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhTMyw_P7BUKc1ICeyf8p5A7lzDp_P_ByGCDka0nWZ9Am25cDHBEEw8EiONzs4Hr5WLvkLEnDydnCpYSw5QQhcVmYXgdkprkchNaxbugVVK_CFwTuu8OSq91-7h0To7JKH5mB-tW4gzLEmsXyqdjkwhyEWGWclTOnuH4fGX_ugq654dCGjGEtPrTHsKG7Q'},
		{text:'Knight of Caster</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgPzZTEnmYiOkHc1Ccfg4tLwZz1coxVjG-M1psJwj5dKWGIrt4_HEHqL5VR4a3jntSsSLLyUlPybq7lOqgQuPLtwPCtGOyQPSK-Q6cDAk0uaIiHCE6JoEJKJQ5Nf2jOTXHGt_-ND8twc0dWqxEsMv7t9u67mfA7UvxigA79LlK8IxQ8pHaS4vgpUWuULlA'},
		{text:'Queen of Caster</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgG7YJQi-32DvA299cHgB6NnfjOCexOQIHCUtB-aKkOkoe3oYlpXtulWXTYcWAt6o_QG-zRkARbXtGUnDCXL_HeP4O3h8w-W2tJkSqJzJsgAHabJZlCMrLavB_6wi2-aQMaSlulG0GHbWfdhcx3CtlFMVe48LxiokgK_vCy_SM3o0qSZ9TaDun7n6ev6cU'},
		{text:'King of Caster</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjWpEXh2kxLBWEumwYu9-2NTMdnnXrLBJmSnO1ugU4xihJ4ypi7_1pg1VwB4lfMw151svWNdA5IzNL6FXaCh2qRSv747VwszOAPg2D1LnZ8h-gDR8wtB_lGr72c3XY44SNcICCVft0Wy35Fzkv8qf8cruGnM53VSxNC5GEYETbdBy9sZIPl8MmUPaESXuk'},
		{text:'Page of Berserker</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiDGIk6UqUFBI8CXK904sv0vVjmt60eYWO7WoqW98iD7DhabDdQHluhdCe2P1TMHk66wt5ql4OGjFhF28PQrPKZh312e0JnMdFRTfYKqhiqE2AHrPrN4lzaMNbOK2hgKzuq7mE6e1WSMlchZT9iETp-11oVFueFSj3VIgxP_qeJvDcZNA1FZVQcQ7Tz2Qc'},
		{text:'Knight of Berserker</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEjVYYyXUgNNa3uqJSlnegVxwQFmDts-g6ewmdeVfXmC444A-sMXGe7dGG0LQXUj39O0w4EC6pCHs27aZNeXUGQOZmfhZ2sX6ggcb0WZOtMcYAzRieX_oURSkzYmQCs8IciOLCU1iA0fcAfYBLbVZE67nGXHSKl_rKBB5-BIfSREV78syURPs-7IQelzmWE'},
		{text:'Queen of Berserker</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEgVK9hIgqjmQMAo-uhoyNPcwxpJTP3cuuO1NrDbY0X175aFkh-c9CvAOc_GuPPhVSuYBJuFOhId6fmXpQPGoCaaiMVBgVcGYvKJDDPbqCD-IKPDUkI8pibFrU_K1T8YtaVOWu2M9Oz5xjdm285lh3Y6GXYVcBcI4q7dgf945GbrIcoPxt0lwZF7OknO8Go'},
		{text:'King of Berserker</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEj97QkdlIqTZVHQbeORbuTF9eOb8Rj_GtmLalFw1N35vDjundl52-VQq8ogZIaekFyMFDEaoblyUgZFi9FT_VtfYM2pAM4hCoOCfnL_bkkrkmCxMt-RJH_c-3yHzFZtNDpa7Khx0H_B0wMwXjlDQe-PxnXGo0vEhaw4r_1ZTQbnv0HdcUrB1pfGb7UPYxI'},
		{text:'Page of Extra</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiaXglySqmnBrvgaZ6iFuGu4fqoK8ZVdow076IMlSAda3kekgEY9jfhZudUCua3BAwT13UIZ_8OzdKe0Yadek_IUFjHUHZYOYU1SPbdhuTgMilCoFYiK6zRmHQJSqhuwfizX9hxxagR8eeXV16pMJyLJO6tUV_x2IHyp_dkftXSK_XtyTbnWn6ofTU9bmM'},
		{text:'Knight of Extra</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEhaXulNyvj63ZthZE_1RIfqM2M2ZWTedHC_H5Hb8nj7IKYZduicGfyEUibwtGCsHPVQDKoV-FkOw3F-O40s2nlWdaXjcB16HAPV_m_QTFdDTgrtWpMYOQbCTNbwr_bvY8digWVUKbO7Mhx-iOrft03Oj3h5khs3FM6urH8QW1Bh56DvOJ-waAdWQjia8Do'},
		{text:'Queen of Extra</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEj--ETH-3QaWnzTG1vHOijv0yhKnONHINH81a7NsATyScFul1gz12Sm3ktstUbv_W25PwENxOS9Q4gJOqy9nTNKwpuwes1RZlI0Wp4Ml1fFusIF9tvU9utDXYq675qe97plNUBzLz1J5y2qQQMXipXETiNTy5T8Tw92UwRJWW7GiZ8K8vuARWO7o2hiMZg'},
		{text:'King of Extra</div>',img:'https://blogger.googleusercontent.com/img/a/AVvXsEiICdsx63ZL5hc0mGs6mT1hEn8EqEfjDAeXE6dUMYFWFrrBhxqS-L6S5tIWju41jhFHzbsZZA7rXBdyMWw--aHdbVHP7Su8_5ZGhhOwT4ll1McFBDq6_93t8IkapKIwLTHKpkH0TuE7h_1PREvuycL4c1smaEiB6df5YSUBmFEs4JL9vIWMrxgFMMtxMXU'},

	];	
	const Umeaning = [	
		{text:'Sự ngu ngốc và thiếu hiểu biết, sự điên rồ, nổi bật giữa đám đông, tìm kiếm sự mới lạ, khả năng vô hạn, tình yêu tự do trong một môi trường mới'},
		{text:'Giao tiếp trôi chảy, suy nghĩ tỉ mỉ, tiến triển thuận lợi, ước mơ thành hiện thực, tình yêu sắp đến, giáo viên giỏi và bạn bè tốt bụng.'},
		{text:'Bí ẩn, tương lai chưa được tiết lộ; sự im lặng và kiên trì; sự khôn ngoan; sự độc lập; tình yêu lý tưởng.'},
		{text:'Mùa màng bội thu, thịnh vượng, nét quyến rũ nữ tính, tài năng nghệ thuật, hôn nhân và sự lãng mạn đầy hứa hẹn, cùng cuộc sống hạnh phúc.'},
		{text:'Có ảnh hưởng sâu sắc đến người hỏi, sở hữu ý chí mạnh mẽ, tinh thần trách nhiệm và bản tính độc đoán nhưng đáng tin cậy; tuy nhiên, có khoảng cách tình cảm và mối quan hệ là với một người đàn ông lớn tuổi hơn.'},
		{text:'Một buổi lễ trang trọng do một nhóm nhà hảo tâm tổ chức; tình yêu Platon; giáo sĩ; người bảo thủ.'},
		{text:'Đối mặt với một quyết định quan trọng, một thách thức về giá trị, một mối tình lãng mạn sắp tới, những cảm xúc hòa hợp và một cơ hội tốt.'},
		{text:'Ý chí mạnh mẽ, chiến thắng, tham vọng, thử thách, lòng can đảm, kín đáo về mặt cảm xúc, giao tiếp hạn chế, tính cách độc lập, tinh thần chiến binh.'},
		{text:'Nhẹ nhàng bên ngoài, mạnh mẽ bên trong; can đảm; tự tin; cống hiến hết mình; hồi phục; tinh thần chiến đấu kiên định; tình yêu nồng nàn; xoa dịu cơn giận.'},
		{text:'Trí tuệ, hiểu biết sâu sắc, suy nghĩ tỉ mỉ, bình tĩnh; cần sự cô độc và tự vấn; tình trạng độc thân; tìm kiếm sự hướng dẫn từ những người thông thái.'},
		{text:'Một sự thay đổi tích cực, sự giàu có bất ngờ, tình yêu sét đánh, vận may, một cuộc hôn nhân định mệnh.'},
		{text:'Một cách tiếp cận công bằng và hợp lý, phối hợp lập trường trung lập và vô tư để tìm kiếm công lý. Trung thực và chính trực.'},
		{text:'Hãy chấp nhận thử thách, hy sinh có ý nghĩa, lắng nghe trái tim và suy nghĩ từ một góc nhìn khác. Hãy hết mình cống hiến.'},
		{text:'Thất bại, thất nghiệp, chấm dứt giao dịch, ly hôn hoặc chia tay, bệnh tật hoặc tai nạn, phá vỡ thói quen hoặc cuộc sống buồn tẻ.'},
		{text:'Một mối quan hệ suôn sẻ và cùng có lợi sẽ dẫn đến hạnh phúc bình thường; sự yêu mến chuyển thành tình yêu - một tình cảm sâu sắc và lâu dài.'},
		{text:'Những cám dỗ không thể cưỡng lại, chủ nghĩa vật chất, sự phục tùng, cuộc sống vô lý, sự độc ác, bệnh tật và những mối tình bí mật. Sự kiêu ngạo.'},
		{text:'Những đòn chí mạng, những thay đổi mạnh mẽ, xung đột, bệnh tật đột ngột, chơi với lửa và bị bỏng, niềm tin sụp đổ, chia ly đột ngột, vỡ mộng về tình yêu.'},
		{text:'Những mong muốn thành hiện thực; tương lai tươi sáng; sự sáng tạo; trí tưởng tượng; mức sống được cải thiện; người bạn đời lý tưởng; mang thai.'},
		{text:'Sự bất an bên trong, lời nói dối, sự hỗn loạn, nguy hiểm, sự say mê, mối tình tay ba và một lựa chọn khó khăn.'},
		{text:'Tràn đầy năng lượng, công việc suôn sẻ, thành công trong học tập và một cuộc hôn nhân hạnh phúc.'},
		{text:'Giải quyết khủng hoảng, thăng tiến, tin tốt, tình yêu hồi sinh, thận trọng, quyết đoán.'},
		{text:'Sự hoàn thiện – Theo đuổi sự hoàn hảo suốt đời, một kết quả đẹp và một mối tình lý tưởng.'},
		{text:'Sự ngu ngốc và thiếu hiểu biết, sự điên rồ, nổi bật giữa đám đông, tìm kiếm sự mới lạ, khả năng vô hạn, tình yêu tự do trong một môi trường mới'},
		{text:'Giao tiếp trôi chảy, suy nghĩ tỉ mỉ, tiến triển thuận lợi, ước mơ thành hiện thực, tình yêu sắp đến, giáo viên giỏi và bạn bè tốt bụng.'},
		{text:'Bí ẩn, tương lai chưa được tiết lộ; sự im lặng và kiên trì; sự khôn ngoan; sự độc lập; tình yêu lý tưởng.'},
		{text:'Mùa màng bội thu, thịnh vượng, nét quyến rũ nữ tính, tài năng nghệ thuật, hôn nhân và sự lãng mạn đầy hứa hẹn, cùng cuộc sống hạnh phúc.'},
		{text:'Có ảnh hưởng sâu sắc đến người hỏi, sở hữu ý chí mạnh mẽ, tinh thần trách nhiệm và bản tính độc đoán nhưng đáng tin cậy; tuy nhiên, có khoảng cách tình cảm và mối quan hệ là với một người đàn ông lớn tuổi hơn.'},
		{text:'Một buổi lễ trang trọng do một nhóm nhà hảo tâm tổ chức; tình yêu Platon; giáo sĩ; người bảo thủ.'},
		{text:'Đối mặt với một quyết định quan trọng, một thách thức về giá trị, một mối tình lãng mạn sắp tới, những cảm xúc hòa hợp và một cơ hội tốt.'},
		{text:'Ý chí mạnh mẽ, chiến thắng, tham vọng, thử thách, lòng can đảm, kín đáo về mặt cảm xúc, giao tiếp hạn chế, tính cách độc lập, tinh thần chiến binh.'},
		{text:'Nhẹ nhàng bên ngoài, mạnh mẽ bên trong; can đảm; tự tin; cống hiến hết mình; hồi phục; tinh thần chiến đấu kiên định; tình yêu nồng nàn; xoa dịu cơn giận.'},
		{text:'Trí tuệ, hiểu biết sâu sắc, suy nghĩ tỉ mỉ, bình tĩnh; cần sự cô độc và tự vấn; tình trạng độc thân; tìm kiếm sự hướng dẫn từ những người thông thái.'},
		{text:'Một sự thay đổi tích cực, sự giàu có bất ngờ, tình yêu sét đánh, vận may, một cuộc hôn nhân định mệnh.'},
		{text:'Một cách tiếp cận công bằng và hợp lý, phối hợp lập trường trung lập và vô tư để tìm kiếm công lý. Trung thực và chính trực.'},
		{text:'Hãy chấp nhận thử thách, hy sinh có ý nghĩa, lắng nghe trái tim và suy nghĩ từ một góc nhìn khác. Hãy hết mình cống hiến.'},
		{text:'Thất bại, thất nghiệp, chấm dứt giao dịch, ly hôn hoặc chia tay, bệnh tật hoặc tai nạn, phá vỡ thói quen hoặc cuộc sống buồn tẻ.'},
		{text:'Một mối quan hệ suôn sẻ và cùng có lợi sẽ dẫn đến hạnh phúc bình thường; sự yêu mến chuyển thành tình yêu - một tình cảm sâu sắc và lâu dài.'},
		{text:'Những cám dỗ không thể cưỡng lại, chủ nghĩa vật chất, sự phục tùng, cuộc sống vô lý, sự độc ác, bệnh tật và những mối tình bí mật. Sự kiêu ngạo.'},
		{text:'Những đòn chí mạng, những thay đổi mạnh mẽ, xung đột, bệnh tật đột ngột, chơi với lửa và bị bỏng, niềm tin sụp đổ, chia ly đột ngột, vỡ mộng về tình yêu.'},
		{text:'Những mong muốn thành hiện thực; tương lai tươi sáng; sự sáng tạo; trí tưởng tượng; mức sống được cải thiện; người bạn đời lý tưởng; mang thai.'},
		{text:'Sự bất an bên trong, lời nói dối, sự hỗn loạn, nguy hiểm, sự say mê, mối tình tay ba và một lựa chọn khó khăn.'},
		{text:'Tràn đầy năng lượng, công việc suôn sẻ, thành công trong học tập và một cuộc hôn nhân hạnh phúc.'},
		{text:'Khủng hoảng được giải quyết, thăng tiến, tin tốt, tình yêu được hồi sinh và đưa ra quyết định sáng suốt.'},
		{text:'Sự hoàn thiện – Theo đuổi sự hoàn hảo suốt đời, một kết quả đẹp và một mối tình lý tưởng.'},
		{text:'Ngây thơ và tốt bụng, dũng cảm và hướng về phía trước, trung thành và không sợ hãi, có sức chiến đấu đáng gờm.'},
		{text:'Tinh thần trẻ trung, nhiệt huyết, kỹ năng lãnh đạo và vai trò chủ đạo trong các mối quan hệ.'},
		{text:'Mục tiêu tuyệt vời, hành động mạnh mẽ, sự kiên trì, tình yêu bình tĩnh, trí tuệ và khả năng nhận ra và sử dụng tài năng. Tiến về phía trước một cách bất khuất'},
		{text:'Phản ứng mạnh mẽ, tích cực; tầm nhìn nghệ thuật; lời nói lưu loát; có tố chất lãnh đạo bẩm sinh.'},
		{text:'Lòng can đảm, lòng hiếu thảo, trí thông minh, coi trọng tình yêu và gia đình, và hợp tác với người khác'},
		{text:'Thừa nhận lỗi lầm và sửa chữa chúng; tự nhận thức; một thế giới quan độc đáo; tình cảm bền vững; luôn có người yêu bên cạnh; và phong thái vương giả.'},
		{text:'Tình yêu nồng nàn; tìm kiếm hạnh phúc cho người khác; ngoại hình đẹp; được ban phước.'},
		{text:'Chủ động cải thiện; chấp nhận thử thách; yêu gia đình; thực tế.. mạnh'},
		{text:'Nghiêm túc, kiên trì, cực kỳ đam mê, rực rỡ, không sợ hãi, theo đuổi lý tưởng'},
		{text:'Gương mặt đẹp, lòng trung thành, sự lịch sự và tuổi trẻ vĩnh cửu; tính kỷ luật tuyệt vời. Được mọi người yêu mến.'},
		{text:'Tình yêu thuần khiết, sự vâng lời, lòng trắc ẩn, kết nối tâm linh, sự kiên trì và quyết đoán.'},
		{text:'Chủ nghĩa anh hùng, lòng trung thành và sự nghiêm trang mang lại sức sống mới; sự tự tin không lay chuyển dẫn đến việc theo đuổi mục tiêu một cách tàn nhẫn.'},
		{text:'Có tính cách nồng nhiệt và không bị kiềm chế, phá vỡ các quy ước, độc lập và phóng khoáng, và mong muốn chia sẻ.'},
		{text:'Lòng từ bi, lòng tốt, tuổi trẻ, sự hiểu biết rõ ràng, ẩn mình, nhìn thấu mọi thứ.'},
		{text:'Tinh thần phiêu lưu; quyết tâm không lay chuyển; kỹ năng giao tiếp tuyệt vời. Con mắt của một doanh nhân.'},
		{text:'Ý thức trách nhiệm cao, tính chính trực, khả năng thừa nhận và sửa chữa sai lầm, coi trọng những người thân yêu, theo đuổi mọi việc đến cùng và trân trọng các mối quan hệ.'},
		{text:'Chủ nghĩa lý tưởng, lòng trung thành, sức quyến rũ phi thường, tài năng âm nhạc, trí thông minh và khả năng chống lại cám dỗ.'},
		{text:'Phương pháp lập quy tắc, ngoại hình nổi bật, quyết tâm, bình tĩnh, tài năng đặc biệt, thịnh vượng và phát triển'},
		{text:'Ngoại hình xinh đẹp, cao quý, điềm tĩnh và bình tĩnh, theo chủ nghĩa hòa bình, kịch tính và là một hành trình từ nghèo đói đến thịnh vượng.'},
		{text:'Lòng trung thành với tình yêu, đức tin, niềm tin vững chắc, quan điểm độc đáo và chịu trách nhiệm'},
		{text:'Tình yêu thuần khiết, ý thức về bản sắc, những câu chuyện cổ tích như mơ, lòng tốt, sự ngây thơ, khái niệm hóa'},
		{text:'Sự kiên định, nhẹ nhàng, bình đẳng và từ bi, tinh thần khám phá, sáng tạo và khả năng chữa lành.'},
		{text:'Chủ động trong tình yêu, tỉ mỉ, chống lại sự cám dỗ, quyến rũ và chiếm hữu.'},
		{text:'Sự tò mò, lãng mạn, niềm đam mê mãnh liệt, sự liều lĩnh, tài năng nghệ thuật, thiên tài và được biết đến.'},
		{text:'Tính cách cao quý, điềm tĩnh, tài năng xuất chúng, tốt bụng, hoàn hảo và có người yêu.'},
		{text:'Hãy dũng cảm từ chối những lời nói ngọt ngào; hãy súc tích và đúng trọng tâm; hãy bình tĩnh và trung thành tuyệt đối.'},
		{text:'Nghiêm túc, trí thức, nhẹ nhàng, thông minh, mạnh mẽ tuyệt đối, có bản năng làm mẹ.'},
		{text:'Cực kỳ trung thành, ngây thơ, kiên định trong lập trường, tin tưởng vào phán đoán của chính mình, một nhà lãnh đạo tinh thần.. Cứu chiến tranh'},
		{text:'Lợi thế tuyệt đối, mất kiểm soát, che giấu sự thật, ngoại hình và nội tâm khác nhau'},
		{text:'Tỉ mỉ, quyết đoán, tôn trọng và quan sát'},
		{text:'Sự trong sáng và bản năng bảo vệ bẩm sinh kiên định, cùng sự sẵn sàng thử những điều mới mẻ.'},
		{text:'Sự bình tĩnh và lòng trung thành; kỹ năng lãnh đạo; nắm vững kiến ​​thức mới; đức tin vững chắc.'},
	];	
	const Rmeaning = [	
		{text:'Trôi dạt, liều lĩnh, liều lĩnh, bỏ lỡ cơ hội, phù phiếm về mặt cảm xúc và thiếu trách nhiệm. Suy đồi.'},
		{text:'Đi chệch hướng, tình hình trở nên mất kiểm soát, báo trước sự thất bại; thiếu chủ động, thiếu quyết đoán; tầm thường; trở ngại trong các mối quan hệ lãng mạn.'},
		{text:'Sự thiếu hiểu biết, tính cách thần kinh, sự kén chọn, rối loạn ám ảnh cưỡng chế, tình yêu không được đáp lại, sự độc thân, sự kiêu ngạo, sự khó chịu về thể chất, mang thai'},
		{text:'Niềm vui đã mất; những thất bại và chuyện tình tan vỡ; sinh nở khó khăn; phá thai; phù phiếm; kiêu ngạo. Lãng phí.'},
		{text:'Tự phụ, non nớt, ý chí yếu đuối, kiêu ngạo, bướng bỉnh, nghiện công việc, tùy tiện, lạnh lùng, chiếm hữu.'},
		{text:'Phá vỡ truyền thống, cô lập và bất lực, tình cảm sâu sắc nhưng số phận nông cạn, sự phụ thuộc, thiếu tin tưởng và bảo thủ quá mức.'},
		{text:'Những thất bại trong tình cảm, mối quan hệ đối tác kém, sự thờ ơ và phản bội, sự bất ổn và những quyết định sai lầm.'},
		{text:'Một thất bại thảm hại, tham vọng quá lớn, mối tình tay ba, một sự cố bất ngờ trong chuyến đi, mất tinh thần chiến đấu, vướng vào xung đột và một đối thủ đáng gờm.'},
		{text:'Sự yếu đuối và bất tài, sợ hãi và nghi ngờ, lạm dụng quyền lực, kiêu ngạo và tự phụ, không có khả năng duy trì tình yêu và các vấn đề về sức khỏe.'},
		{text:'Mất cảnh giác, bướng bỉnh, cô đơn, xa lánh xã hội, cảnh giác quá mức và nghi ngờ về tình yêu.'},
		{text:'Những thay đổi không may, sự thiếu quyết đoán, cơ hội bị bỏ lỡ, thất bại, không phù hợp để đầu cơ, đau khổ, tình yêu ngắn ngủi.'},
		{text:'Sự bất công, hợp đồng gian lận, quyết định sai lầm, tranh chấp, kiện tụng—một tình huống khó giải quyết mà cả hai bên đều khó có thể giải quyết. Trốn tránh trách nhiệm.'},
		{text:'Những cá nhân bướng bỉnh và ích kỷ, bị ràng buộc bởi môi trường, hy sinh vô nghĩa. Tổn hại về thể chất; kết thúc giai đoạn bế tắc.'},
		{text:'Một tia hy vọng sau một thời gian dài tăm tối; một khởi đầu mới trong quá trình phục hồi; sự bướng bỉnh; suy nghĩ về quá khứ.'},
		{text:'Lãng phí, khó cân bằng, thiếu hiểu biết trong tình yêu, công việc không ổn định và hợp tác không hài hòa.'},
		{text:'Được giải thoát khỏi những ràng buộc về vật chất, chống lại những cám dỗ, chữa lành bệnh tật, cắt đứt những ràng buộc về tình cảm, sự chia ly và một mối quan hệ đầy rẫy tình yêu và hận thù.'},
		{text:'Trong tình thế khó khăn; tình huống cấp bách; vấn đề tội phạm; khủng hoảng tình yêu; phải trả giá cho sự kiêu ngạo.'},
		{text:'Sự thất vọng, thất bại, mọi việc không diễn ra như kế hoạch, những tưởng tượng không thực tế, theo đuổi tình yêu một cách vô vọng, tình yêu với rất ít hy vọng.'},
		{text:'Thoát khỏi trò lừa đảo, giải quyết hiểu lầm, mọi thứ sẽ được cải thiện, thoát khỏi thảm họa bằng sự sáng suốt và chờ thời gian để giải quyết vấn đề.'},
		{text:'Chán nản, mối quan hệ giữa các cá nhân kém, thất nghiệp, mối quan hệ tình cảm không chắc chắn, ly hôn và diễn biến bất lợi trong tình hình.'},
		{text:'Tin xấu: quyết định đã bị hoãn lại, và sẽ mất rất nhiều thời gian để mọi thứ được cải thiện. Tình yêu không được chấp nhận. Một tình yêu không muốn buông bỏ, tất cả đều vô ích.'},
		{text:'Không đạt được mục tiêu; thất bại do chuẩn bị không đầy đủ; tiến triển chậm; trạng thái tinh thần kém; thiếu sự khéo léo.'},
		{text:'Trôi dạt, liều lĩnh, liều lĩnh, bỏ lỡ cơ hội, phù phiếm về mặt cảm xúc và thiếu trách nhiệm. Suy đồi.'},
		{text:'Đi chệch hướng, tình hình trở nên mất kiểm soát, báo trước sự thất bại; thiếu chủ động, thiếu quyết đoán; tầm thường; trở ngại trong các mối quan hệ lãng mạn.'},
		{text:'Sự thiếu hiểu biết, tính cách thần kinh, sự kén chọn, rối loạn ám ảnh cưỡng chế, tình yêu không được đáp lại, sự độc thân, sự kiêu ngạo, sự khó chịu về thể chất, mang thai'},
		{text:'Niềm vui đã mất; những thất bại và chuyện tình tan vỡ; sinh nở khó khăn; phá thai; phù phiếm; kiêu ngạo. Lãng phí.'},
		{text:'Tự phụ, non nớt, ý chí yếu đuối, kiêu ngạo, bướng bỉnh, nghiện công việc, tùy tiện, lạnh lùng, chiếm hữu.'},
		{text:'Phá vỡ truyền thống, cô lập và bất lực, tình cảm sâu sắc nhưng số phận nông cạn, sự phụ thuộc, thiếu tin tưởng và bảo thủ quá mức.'},
		{text:'Những thất bại trong tình cảm, mối quan hệ đối tác kém, sự thờ ơ và phản bội, sự bất ổn và những quyết định sai lầm.'},
		{text:'Một thất bại thảm hại, tham vọng quá lớn, mối tình tay ba, một sự cố bất ngờ trong chuyến đi, mất tinh thần chiến đấu, vướng vào xung đột và một đối thủ đáng gờm.'},
		{text:'Sự yếu đuối và bất tài, sợ hãi và nghi ngờ, lạm dụng quyền lực, kiêu ngạo và tự phụ, không có khả năng duy trì tình yêu và các vấn đề về sức khỏe.'},
		{text:'Mất cảnh giác, bướng bỉnh, cô đơn, xa lánh xã hội, cảnh giác quá mức và nghi ngờ về tình yêu.'},
		{text:'Những thay đổi không may, sự thiếu quyết đoán, cơ hội bị bỏ lỡ, thất bại, không phù hợp để đầu cơ, đau khổ, tình yêu ngắn ngủi.'},
		{text:'Sự bất công, hợp đồng gian lận, quyết định sai lầm, tranh chấp, kiện tụng—một tình huống khó giải quyết mà cả hai bên đều khó có thể giải quyết. Trốn tránh trách nhiệm.'},
		{text:'Những cá nhân bướng bỉnh và ích kỷ, bị ràng buộc bởi môi trường, hy sinh vô nghĩa. Tổn hại về thể chất; kết thúc giai đoạn bế tắc.'},
		{text:'Một tia hy vọng sau một thời gian dài tăm tối; một khởi đầu mới trong quá trình phục hồi; sự bướng bỉnh; suy nghĩ về quá khứ.'},
		{text:'Lãng phí, khó cân bằng, thiếu hiểu biết trong tình yêu, công việc không ổn định và hợp tác không hài hòa.'},
		{text:'Được giải thoát khỏi những ràng buộc về vật chất, chống lại những cám dỗ, chữa lành bệnh tật, cắt đứt những ràng buộc về tình cảm, sự chia ly và một mối quan hệ đầy rẫy tình yêu và hận thù.'},
		{text:'Trong tình thế khó khăn; tình huống cấp bách; vấn đề tội phạm; khủng hoảng tình yêu; phải trả giá cho sự kiêu ngạo.'},
		{text:'Sự thất vọng, thất bại, mọi việc không diễn ra như kế hoạch, những tưởng tượng không thực tế, theo đuổi tình yêu một cách vô vọng, tình yêu với rất ít hy vọng.'},
		{text:'Thoát khỏi trò lừa đảo, giải quyết hiểu lầm, mọi thứ sẽ được cải thiện, thoát khỏi thảm họa bằng sự sáng suốt và chờ thời gian để giải quyết vấn đề.'},
		{text:'Chán nản, mối quan hệ giữa các cá nhân kém, thất nghiệp, mối quan hệ tình cảm không chắc chắn, ly hôn và diễn biến bất lợi trong tình hình.'},
		{text:'Tin xấu: quyết định đã bị hoãn lại, và sẽ mất rất nhiều thời gian để mọi thứ được cải thiện. Tình yêu không được chấp nhận. Một tình yêu dai dẳng, miễn cưỡng—tất cả đều vô ích.'},
		{text:'Không đạt được mục tiêu; thất bại do chuẩn bị không đầy đủ; tiến triển chậm; trạng thái tinh thần kém; thiếu sự khéo léo.'},
		{text:'Bị bệnh tật hành hạ; chỉ còn một bước nữa là thành công; bỏ cuộc giữa chừng; không phân biệt được đúng sai; cố chấp giữ vững quan điểm của mình.'},
		{text:'Không thể giữ bình tĩnh; bị phản bội; nghi ngờ; mất mục tiêu; hoang tưởng; không thể tha thứ cho lỗi lầm của người khác.'},
		{text:'Khủng bố, tuyệt vọng, tàn nhẫn, hủy diệt, hoang tưởng, coi thường người khác, phá vỡ sự cân bằng'},
		{text:'Phương pháp tàn ác, bản tính kiểm soát, xu hướng bạo lực, ham muốn mãnh liệt và xu hướng làm hại người khác.'},
		{text:'Sự kiêu ngạo, sự bất cẩn, sự trốn tránh thực tại, sự tự mâu thuẫn, sự hỗn loạn và sự nhầm lẫn.'},
		{text:'Thỏa mãn trí tò mò và hành động bốc đồng; chấp nhận rủi ro; nhầm lẫn giữa tưởng tượng và thực tế; kiêu ngạo và phóng đại; tự tin mù quáng.'},
		{text:'Can thiệp vào chuyện tình cảm của người khác; đầy ham muốn; hỗn loạn; ép buộc.'},
		{text:'Nó mang lại gánh nặng cho những người xung quanh bạn; nó khiến bạn trở nên nghiêm túc; nó kìm nén cảm xúc của bạn; nó khiến bạn bị ám ảnh.. Kế hoạch bị chặn'},
		{text:'Sự kiêu ngạo, khát máu, tưởng tượng phi thực tế, trống rỗng, những ham muốn không được thỏa mãn, nghiện ngập'},
		{text:'Những rắc rối, mối quan hệ không may mắn, sự phản bội, tự trách, mắc sai lầm gây ra sự ghen tị'},
		{text:'Sự khiêm nhường, cáu kỉnh, hiểu lầm người khác, bị che mắt bởi lời nói dối và tình yêu méo mó, ám ảnh.'},
		{text:'Những ham muốn kiêu ngạo và mâu thuẫn, không có khả năng đối mặt với thực tế, chìm đắm trong quá khứ, tàn nhẫn và nhẫn tâm. Bị hiểu lầm.'},
		{text:'Không phân biệt được đúng sai; tuân theo một cách mù quáng; không có khả năng tự bảo vệ mình.. Tham lam vì tiền'},
		{text:'Quan hệ bừa bãi, bối rối, thiếu kế hoạch dài hạn và lý tưởng hóa.'},
		{text:'Lòng tham, chủ nghĩa khoái lạc, hỗn loạn, lãng phí, cướp bóc người khác và hiệu suất giảm sút giữa chừng.'},
		{text:'Tàn bạo, cáu kỉnh, không trung thực, cực đoan, sinh ra đã có khuyết điểm, không hoàn thiện'},
		{text:'Sự phù phiếm, hỗn loạn, những con đường khác nhau, những kẻ đầu cơ, một nơi lang thang và cám dỗ.'},
		{text:'Chinh phục trái tim và khối óc, tranh giành quyền lực, bóng tối, ác ý, bóng tối đằng sau sự quyến rũ'},
		{text:'Sự kiêu ngạo dẫn đến tự hành hạ, hoang tưởng, mong muốn kiểm soát và cuối cùng là không có kết quả gì.. Cái kết bất ngờ dù đã cố gắng'},
		{text:'Rối loạn ám ảnh cưỡng chế, kiểm soát người khác bằng thủ đoạn, tiêu xài hoang phí, cảm thấy thua kém, đánh nhau với đồng loại, khác biệt với người khác'},
		{text:'Bóng tối, đắm chìm trong tình yêu phi thực tế, bạo lực bằng lời nói, sự bắt chước mù quáng và sự tàn ác không phù hợp với vẻ bề ngoài.'},
		{text:'Bướng bỉnh, tự mâu thuẫn, không kiềm chế, buông thả bản thân và không theo khuôn mẫu.'},
		{text:'Cạm bẫy tình yêu; trả thù; nồng nhiệt; vô tư; dễ bị nhìn thấu; mọi thứ không diễn ra như kế hoạch.'},
		{text:'Bướng bỉnh, cố chấp, dễ tìm kiếm nguy hiểm, chia rẽ, điên rồ, đầy ý tưởng, thiếu ham muốn.'},
		{text:'Yếu đuối và non nớt; tự trách bản thân quá mức và không có khả năng phân biệt đúng sai; phản bội bạn bè; hối hận; ám ảnh.'},
		{text:'hiếu chiến, máu lạnh, bi quan, đòi hỏi, vô nhân đạo'},
		{text:'Ham muốn kiểm soát, cực đoan, tình yêu mù quáng, mặc cảm tự ti, tính chiếm hữu'},
		{text:'Chỉ trích người khác, kiêu ngạo, tự mâu thuẫn, ám ảnh, mất bạn đồng hành'},
		{text:'Khả năng hạn chế, chia rẽ, mâu thuẫn, cám dỗ, mất phương hướng'},
		{text:'Kiêu ngạo, ăn nói sắc sảo, mất tình yêu, lừa dối và lạnh lùng.'},
		{text:'Nền phức tạp. Lòng tự trọng thấp, không muốn đối mặt với chính mình; bối rối; thiếu quyết đoán; mất mát những thứ quan trọng.'},
		{text:'Không coi trọng mọi thứ, tin tưởng người khác một cách mù quáng, là kẻ độc tài và dễ thất bại vào phút cuối.. Bất lực để chống cự'},

	];	
//End Data	